services:
  app:
    build: .
    container_name: image-reading
    command: yarn dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - 'db'
    networks:
      - net
  db:
    image: mysql:5.7.31
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'image_reading'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - net
volumes:
  db:

networks:
  net:
